version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:12
  working_directory: ~/action-sync-branches

npm_cache_key: &npm_cache_key
  v1-node-modules-cache-{{ checksum "package-lock.json" }}

restore_node_modules_cache: &restore_node_modules_cache
  restore_cache:
    keys:
      - *npm_cache_key
      - v1-node-modules-cache-

jobs:
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_node_modules_cache
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: *npm_cache_key
  lint:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_node_modules_cache
      - run: npm run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_node_modules_cache
      - run: npm run test

workflows:
  version: 2.1
  build:
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - test:
          requires:
            - dependencies
