name: Sync master/develop branches

on:
  push:
    branches:
      - master

jobs:
  create_sync_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-title: "chore: merge master into develop"
          pr-reviewers: scurker,stephenmathieson
          pr-labels: chore