name: Update major release tag

on:
  push:
    branches:
      - tag-major-releases

jobs:
  update_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          VERSION=$(node -p 'require("./package.json").version')
          MAJOR_VERSION="${VERSION%%.*}
          git tag -f -a "v$MAJOR_VERSION"
          git push origin "refs/tags/v$MAJOR_VERSION"