name: Update major release tag

on:
  push:
    branches:
      - tag-major-releases

jobs:
  update_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          VERSION=$(node -p 'require("./package.json").version')
          MAJOR_VERSION="${VERSION%%.*}"

          if [ -z "$VERSION" ] || [ -z "$MAJOR_VERSION" ]; then
            echo "VERSION or MAJOR_VERSION cannot be empty"
            exit 1
          fi

          git tag -f -a "v$MAJOR_VERSION" -m "update v$MAJOR_VERSION tag"
          git push -f origin "refs/tags/v$MAJOR_VERSION"